# Generated by Django 3.0.3 on 2020-02-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='hire_on',
        ),
        migrations.RemoveField(
            model_name='car',
            name='return_on',
        ),
    ]
