# Generated by Django 3.0.3 on 2020-02-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_message',
        ),
    ]
